name: deploy
on:
  push:
    branches:
      - "release-**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    id: deploySubsquid
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install @subsquid/cli
        run: npm install --location=global @subsquid/cli
      - name: auth subsquid
        run: |
          BRANCH=${{ github.ref_name }}
          PREFIX="release-"
          VERSION=${BRANCH/#$PREFIX}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          sqd auth -k ${{ secrets.DEPLOYMENT_KEY }}
      - name: deploy subsquid
        id: deploySubsquid
        run: sqd squid release test-rubick@${{ env.VERSION }} -v
  update:
    runs-on: ubuntu-latest
    if: steps.deploySubsquid.outcome == 'failure'
    needs: deploy
    steps:
      - name: update subsquid
        run: sqd squid update test-rubick@${{ env.VERSION }} -v
