name: deploy
on:
  push:
    branches:
      - "release-**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install @subsquid/cli
        run: npm install --location=global @subsquid/cli
      - name: get version
        run: |
          BRANCH=${{ github.ref_name }}
          PREFIX="release-"
          VERSION=${BRANCH/#$PREFIX}
          echo ::set-output name=version::$VERSION
      - name: auth subsquid
        run: sqd auth -k ${{ secrets.DEPLOYMENT_KEY }}
      - name: deploy subsquid
        run: sqd squid release test-rubick@${{ steps.vars.outputs.version }} -v
